name: Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    name: PR/Client
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: '**/yarn.lock'
          node-version: 18
          cache: "yarn"

      - name: Install Dependencies (Client)
        working-directory: ./client
        run: yarn --frozen-lockfile

      - name: Go into client
        working-directory: ./client
        run: | 
          yarn lint
          yarn test

      - name: Install Dependencies (Server)
        working-directory: ./server
        run: yarn --frozen-lockfile

      - name: Go into server
        working-directory: ./server
        run: |
          yarn lint