export const FlowData = [
  {
    img: 'https://picsum.photos/200/300',
    name: 'OluwaSegun Idowu',
    position: 'First Contribution',
    contributing: '₦50,000',
    withdrawing: '₦0',
    fee: '₦0',
    nextCashOut: 'May30',
    recentCashOut: 'May 17',
    status: 'Active',
  },
  {
    img: 'https://picsum.photos/200/300',
    name: 'Daniel Jegede',
    position: 'Second Contribution',
    contributing: '₦50,000',
    withdrawing: '₦0',
    fee: '₦0',
    nextCashOut: 'May 31',
    recentCashOut: 'May 18',
    status: 'Inactive',
  },
  {
    img: 'https://picsum.photos/200/300',
    name: 'OluwaSegun Idowu',
    position: 'First Contribution',
    contributing: '₦50,000',
    withdrawing: '₦0',
    fee: '₦0',
    nextCashOut: 'May 30',
    recentCashOut: 'May 17',
    status: 'Offline',
  },
]
