export const GroupData = [
  {
    groupStatus: 'Waiting',
    groupImg: 'https://picsum.photos/200/300',
    groupName: 'Money Palava Savers',
    groupDesc:
      'Make we save together, chop better life! Join this group if you want to flex and still save money for better days. We go show you as money fit run belle and still dey for account.',
    contribution: 500000,
    expectedWithdrawal: 3500000,
    savingFrequency: 'Monthly',
    Duration: 7,
    allMembers: 6,
    groupMembers: [
      {
        slot: 4,
        firstName: 'Anastasie',
        lastName: 'Squibb',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 2,
        firstName: 'Garvin',
        lastName: 'Reimers',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 6,
        firstName: 'Isahella',
        lastName: 'Leatherbarrow',
        image: 'https://picsum.photos/200/300',
      },

      {
        slot: 1,
        firstName: 'Kelcie',
        lastName: 'Donisi',
        image: 'https://picsum.photos/200/300',
      },
    ],
  },
  {
    groupStatus: 'Waiting',
    groupImg: 'https://picsum.photos/200/300',
    groupName: 'Money Palava Savers',
    groupDesc:
      'Make we save together, chop better life! Join this group if you want to flex and still save money for better days. We go show you as money fit run belle and still dey for account.',
    contribution: 500000,
    expectedWithdrawal: 3500000,
    savingFrequency: 'Monthly',
    Duration: 7,
    allMembers: 4,
    groupMembers: [
      {
        slot: 4,
        firstName: 'Anastasie',
        lastName: 'Squibb',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 2,
        firstName: 'Jackson',
        lastName: 'Cheney',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 1,
        firstName: 'Kelcie',
        lastName: 'Donisi',
        image: 'https://picsum.photos/200/300',
      },
    ],
  },
  {
    groupStatus: 'Waiting',
    groupImg: 'https://picsum.photos/200/300',
    groupName: 'Sabi-Sabi Slay Queens',
    groupDesc:
      'Attention Slay Queens! Una wey sabi fashion and glam, join this group make we save money for the latest trends and slay effortlessly. No dulling, we go blend fashion and savings like jollof rice and chicken!',
    contribution: 500000,
    expectedWithdrawal: 3500000,
    savingFrequency: 'Daily',
    Duration: 8,
    allMembers: 30,
    groupMembers: [
      {
        slot: 11,
        firstName: 'Nomi',
        lastName: 'Davioud',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 28,
        firstName: 'Noell',
        lastName: 'Greensmith',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 6,
        firstName: 'Alvan',
        lastName: 'Boddy',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 23,
        firstName: 'Lewiss',
        lastName: 'Bodemeaid',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 3,
        firstName: 'Berget',
        lastName: 'Fearnyough',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 10,
        firstName: 'Temple',
        lastName: 'Keen',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 14,
        firstName: 'Ingra',
        lastName: 'Brasher',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 4,
        firstName: 'Hyman',
        lastName: 'Gawen',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 27,
        firstName: 'Dell',
        lastName: 'Hayselden',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 22,
        firstName: 'Maury',
        lastName: 'Fromant',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 28,
        firstName: 'Kippie',
        lastName: 'Balassi',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 8,
        firstName: 'Salome',
        lastName: 'Gippes',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 25,
        firstName: 'Carolus',
        lastName: 'Angell',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 30,
        firstName: 'Levy',
        lastName: 'Darte',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 16,
        firstName: 'Stevie',
        lastName: 'Ledley',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 31,
        firstName: 'Rebekkah',
        lastName: 'Moreno',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 1,
        firstName: 'Frederich',
        lastName: 'Brookbank',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 19,
        firstName: 'Estell',
        lastName: 'Chastand',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 2,
        firstName: 'Karlie',
        lastName: 'Bartolomivis',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 20,
        firstName: 'Ally',
        lastName: 'Greenway',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 15,
        firstName: 'Ella',
        lastName: 'Dugall',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 12,
        firstName: 'Niko',
        lastName: 'Trouel',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 13,
        firstName: 'Myrtle',
        lastName: 'Huortic',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 26,
        firstName: 'Phylis',
        lastName: 'Possek',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 9,
        firstName: 'Louise',
        lastName: 'Esby',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 24,
        firstName: 'Lucila',
        lastName: 'Fontes',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 5,
        firstName: 'Adiana',
        lastName: 'Rainsden',
        image: 'https://picsum.photos/200/300',
      },
    ],
  },
  {
    groupStatus: 'Waiting',
    groupImg: 'https://picsum.photos/200/300',
    groupName: 'Naija Travel Squad',
    groupDesc:
      'If you be proper ajala, join this group sharp sharp! We dey save money to explore Naija and beyond. From Lagos to Calabar, Abuja to Port Harcourt, we go waka waka together and scatter ground!',
    contribution: 500000,
    expectedWithdrawal: 4000000,
    savingFrequency: 'Monthly',
    Duration: 8,
    allMembers: 32,
    groupMembers: [
      {
        slot: 11,
        firstName: 'Nomi',
        lastName: 'Davioud',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 28,
        firstName: 'Noell',
        lastName: 'Greensmith',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 6,
        firstName: 'Alvan',
        lastName: 'Boddy',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 23,
        firstName: 'Lewiss',
        lastName: 'Bodemeaid',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 3,
        firstName: 'Berget',
        lastName: 'Fearnyough',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 10,
        firstName: 'Temple',
        lastName: 'Keen',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 14,
        firstName: 'Ingra',
        lastName: 'Brasher',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 4,
        firstName: 'Hyman',
        lastName: 'Gawen',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 27,
        firstName: 'Dell',
        lastName: 'Hayselden',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 22,
        firstName: 'Maury',
        lastName: 'Fromant',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 28,
        firstName: 'Kippie',
        lastName: 'Balassi',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 8,
        firstName: 'Salome',
        lastName: 'Gippes',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 25,
        firstName: 'Carolus',
        lastName: 'Angell',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 30,
        firstName: 'Levy',
        lastName: 'Darte',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 16,
        firstName: 'Stevie',
        lastName: 'Ledley',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 31,
        firstName: 'Rebekkah',
        lastName: 'Moreno',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 1,
        firstName: 'Frederich',
        lastName: 'Brookbank',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 19,
        firstName: 'Estell',
        lastName: 'Chastand',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 2,
        firstName: 'Karlie',
        lastName: 'Bartolomivis',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 20,
        firstName: 'Ally',
        lastName: 'Greenway',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 15,
        firstName: 'Ella',
        lastName: 'Dugall',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 12,
        firstName: 'Niko',
        lastName: 'Trouel',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 13,
        firstName: 'Myrtle',
        lastName: 'Huortic',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 26,
        firstName: 'Phylis',
        lastName: 'Possek',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 9,
        firstName: 'Louise',
        lastName: 'Esby',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 24,
        firstName: 'Lucila',
        lastName: 'Fontes',
        image: 'https://picsum.photos/200/300',
      },
      {
        slot: 5,
        firstName: 'Adiana',
        lastName: 'Rainsden',
        image: 'https://picsum.photos/200/300',
      },
    ],
  },
]
